### PR TITLE
Support acquiring a token with a client provided, pre-signed JWT

### PR DESCRIPTION
**Pull request by lochiiconnectivity**
Useful for where the signing takes place externally for example using Azure Key Vault (AKV).
AKV sample included.

### CODE REVIEW

**Comment by lochiiconnectivity** [comment]
Nudge?

**Comment by rayluo** [comment]
Hi @lochiiconnectivity, sorry for the delay as we've been focusing on ADAL Python's successor, the [MSAL Python](https://github.com/AzureAD/microsoft-authentication-library-for-python).

Now taking a close look into your PR, can you tell us what is the functionality difference between your PR and [this existing ADAL Python API](https://adal-python.readthedocs.io/en/latest/#adal.AuthenticationContext.acquire_token_with_client_certificate), [its implementation](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/c9f3c80fb8d71cd2e38e639b28a9138eb4bcd602/adal/token_request.py#L358-L375), and [its sample](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/c9f3c80fb8d71cd2e38e639b28a9138eb4bcd602/sample/certificate_credentials_sample.py)?

**Comment by lochiiconnectivity** [comment]
Hi @rayluo 

>Now taking a close look into your PR, can you tell us what is the functionality difference between your PR and this existing ADAL Python API,

Easy question to answer.

**acquire_token_with_client_certificate** requires a copy of the private key. In this case **I don't have it** , I entrusted it to [Azure Key Vault](https://azure.microsoft.com/en-gb/services/key-vault/) so I need to use the vault API to sign the JWT outside of your library.

This concept certainly does not exist in ADAL Python and I can't see it in MSAL Python either.

Dave

**Comment by rayluo** [comment]
Thanks Dave! Yes I figure that would be your reasoning. It is just in your sample it seems to have access to a cert, therefore the confusion. Would you mind to get in touch with me (see my email in my profile) and then I can better understand your actual usage pattern?

**Comment by lochiiconnectivity** [comment]
That's the cert key **name** in the vault, I've just picked a bad name for the variable, 

here is the sign prototype from the key vault client:

`
    def sign(
            self, vault_base_url, key_name, key_version, algorithm, value, custom_headers=None, raw=False, **operation_config):
        """Creates a signature from a digest using the specified key.

        The SIGN operation is applicable to asymmetric and symmetric keys
        stored in Azure Key Vault since this operation uses the private portion
        of the key. This operation requires the keys/sign permission.

        :param vault_base_url: The vault name, for example
         https://myvault.vault.azure.net.
        :type vault_base_url: str
        :param key_name: The name of the key.
        :type key_name: str
`

**Comment by rayluo** [comment]
Thanks for David's effort to [port this PR to MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/271). Closing this PR here in ADAL.

**Pull request closed without merging**
