### PR TITLE
fix encoding error when format error text (python 2.7 only)

### PR DESCRIPTION
**Pull request by yugangw-msft**
The real error was hidden under the exception of `'ascii' codes can't encode character u'\xa0' in position 150: ordinal not in range(128)`. This is confusing

### CODE REVIEW

**Comment by yugangw-msft** [comment]
//cc: @rayluo could you review and comment?

**Comment by rayluo** [comment]
To document the background, the error happens when the raw error message (unexpectedly?) contains unicode. So we need to force our code base uses unicode in the error message template. This is a demonstration.

    Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> "say {}".format(u"hello \xa0 world")
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 6: ordinal not in range(128)
    >>> u"say {}".format(u"hello \xa0 world")
    u'say hello \xa0 world'
    >>>

The fix looks good to me. :ship:

**Comment by yugangw-msft** [comment]
@rayluo, I have updated couple of more files with the kind of changes. Could you take one more look? I have tested both 2.7 and 3.5 on windows and mac.

**Comment by rayluo** [comment]
LGTM. :ship:

**Pull request merged**
