### PR TITLE
Handle token refresh in Azure Stack (ADFS 2016) 

### PR DESCRIPTION
**Pull request by yugangw-msft**
@rayluo, I will add you to a mail thread with more details
For context, Azure Stack environment uses ADFS 2016. When use MRRT (`multi resource refresh token`) to get an access token for other resources, server doesn't include `resource` in the response payload because it doesn't return a new refresh token. Note, AAD always returns a new refresh token. The consequence is pretty severe, as `resource` is part of the token cache key, and not updating it will corrupt the whole cache.
The change is pretty safe. If you are fine with the option, I will go ahead and add a few test coverage.

### CODE REVIEW

**Comment by yugangw-msft** [comment]
@rayluo, test was added. Please review
//cc: @viananth @bganapa @mayurid

**Comment by viananth** [comment]
@rayluo, could you please review this? This is a blocking scenario for Azure Stack

**Comment by rayluo** [comment]
Merged. A new release is coming soon.

**Comment by rayluo** [comment]
@viananth @bganapa @yugangw-msft FYI: ADAL Python 0.4.7 has been released. As usual, you can get it by `pip install adal`

**Pull request merged**
