### PR TITLE
Changed info log level to debug log level for debug logs

### PR DESCRIPTION
**Pull request by Cloudenius**
Related to issue https://github.com/AzureAD/azure-activedirectory-library-for-python/issues/122. I'm only addressing the log entries I think should be debug instead of logging. Not sure about the other logging mentioned in the issue.

### CODE REVIEW

**Comment by rayluo** [comment]
Thanks @Cloudenius ! This PR itself looks straightforward. We will take a close look on how many other logs (if any) would also need same treatment.

**Comment by Cloudenius** [comment]
> 
> 
> Thanks @Cloudenius ! This PR itself looks straightforward. We will take a close look on how many other logs (if any) would also need same treatment.

Thanks @rayluo.

Any idea when this PR can be reviewed/approved/merged? Thanks!

**Comment by rayluo** [comment]
@Cloudenius et al: although not (yet?) advertised, we have been working on the cousin of ADAL Python, named [MSAL Python](https://github.com/AzureAD/microsoft-authentication-library-for-python) since last 6+ months. And we are currently working on [a new milestone](https://github.com/AzureAD/microsoft-authentication-library-for-python/milestone/1) of it, which will be finished really soon. After that we will come back to take a look at this PR.

PS: In MSAL Python, there is no such info level log in the first place.

**Comment by Cloudenius** [comment]
> 
> 
> @Cloudenius et al: although not (yet?) advertised, we have been working on the cousin of ADAL Python, named [MSAL Python](https://github.com/AzureAD/microsoft-authentication-library-for-python) since last 6+ months. And we are currently working on [a new milestone](https://github.com/AzureAD/microsoft-authentication-library-for-python/milestone/1) of it, which will be finished really soon. After that we will come back to take a look at this PR.
> 
> PS: In MSAL Python, there is no such info level log in the first place.

Thanks @rayluo - looking forward to it. Do note that I've [created a PR with Home Assistant](https://github.com/home-assistant/home-assistant/pull/21366) to get Azure DNS integrated in their platform by using this library. Being able to address this issue would really help getting the component approved.

**Comment by markmabe** [comment]
@Cloudenius  Hi any chance we can squeeze in a modification to the log here and change it to debug also? https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/442d859f7349c5cb079bd81fe0f26fefcf679c5b/adal/token_request.py#L266

It does seem like many of these log statements should be modified. The logging leads the developer to believe it is getting a new token every time, when it may just be returning a cached token. Seems like it should be modified to where if it gets the token from cache it does: **self._log.debug("Using token from cache")** or if not in cache it logs **self._log.debug("Getting token with client credentials.")**

Maybe that will be down the road and outside your straight forward pull request

**Comment by Cloudenius** [comment]
> @Cloudenius Hi any chance we can squeeze in a modification to the log here and change it to debug also?
> 
> [azure-activedirectory-library-for-python/adal/token_request.py](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/442d859f7349c5cb079bd81fe0f26fefcf679c5b/adal/token_request.py#L266)
> 
> Line 266 in [442d859](/AzureAD/azure-activedirectory-library-for-python/commit/442d859f7349c5cb079bd81fe0f26fefcf679c5b)
> 
>  self._log.info("Acquiring token with username password.") 
> It does seem like many of these log statements should be modified. The logging leads the developer to believe it is getting a new token every time, when it may just be returning a cached token. Seems like it should be modified to where if it gets the token from cache it does: **self._log.debug("Using token from cache")** or if not in cache it logs **self._log.debug("Getting token with client credentials.")**
> 
> Maybe that will be down the road and outside your straight forward pull request

Sure, it's in the PR now. :) See commit c988261628e0f162151fad9f99c698113a7e94de.

**Comment by Cloudenius** [comment]
Thanks @rayluo! 👍  Any idea when the new version will be released?

**Comment by rayluo** [comment]
Yeah I think @abhidnya13 and I can release a patch version 1.2.2 for this one soon.

Meanwhile, I just want to make sure @Cloudenius is aware that, this PR is just a mitigation, but not a full solution. The moment when you would like to enable all the debug logs for YOUR OWN script, all those ADAL debugging log would come back. The ultimate and canonical solution is actually mentioned in [this comment inside issue 122](https://github.com/AzureAD/azure-activedirectory-library-for-python/issues/122#issuecomment-483433102).

**Comment by Cloudenius** [comment]
Yes I understand @rayluo, thanks!

**Pull request merged**
